### ISSUE TITLE
我看这个项目很好啊,可是一年多没有维护了,Lzccug你是不打算再维护了么?

### ISSUE THREAD

**Issue by wuxiaolan91** [Lzccug/ImageCompression#1]
我看这个项目很好啊,可是一年多没有维护了,Lzccug你是不打算再维护了么?

**Comment by Lzccug** [comment]
哦  因为这个目前的项目不怎么用到这个，所以不怎么维护了。
不过要维护的话会从压缩选项，比如要压缩到的大小这样的功能出发维护吧，
还有个是压缩时的性能；
建议你有兴趣的话可以尝试在这里新建个分支出去维护哦。

**Comment by wuxiaolan91** [comment]
你是说用户设置要压缩到多少kb？
还是说什么，
因为你的项目现在已经支持用户自己设置宽高了嘛。
我已经在我的项目里用上你这个插件了。
感谢你的辛劳。
好啊。呵呵。
